BOT_TOKEN = "5087360618:AAFBZbKjebowumFneCkpPcY1l2eB88y9_3M"

DATA_DIRECTORY = "data"
THUMBNAILS_DIRECTORY = f"{DATA_DIRECTORY}/thumbnails"

EVENTS_FILE = f"{DATA_DIRECTORY}/events.json"
CHANNELS_FILE = f"{DATA_DIRECTORY}/channels.json"
ADMINS_FILE = f"{DATA_DIRECTORY}/admins.json"
