MAX_MESSAGES = 10

ENCODING = "UTF-8"
DATA_DIRECTORY = "data"

THUMBNAILS_FORMAT = "jpg"

EVENTS_FILE = f"{DATA_DIRECTORY}/events.json"
ADMINS_FILE = f"{DATA_DIRECTORY}/admins.json"
CHANNELS_FILE = f"{DATA_DIRECTORY}/channels.json"

THUMBNAILS_DIRECTORY = f"{DATA_DIRECTORY}/thumbnails/"

BOT_TOKEN = "5087360618:AAFBZbKjebowumFneCkpPcY1l2eB88y9_3M"
